[theme]
base = "dark"
primaryColor = "#FFFFFF"
backgroundColor = "#1A1A1A"
secondaryBackgroundColor = "#212121"
textColor = "#FFFFFF"
font = "sans-serif"
pageBackgroundColor = "#1A1A1A"
sidebarBackgroundColor = "#2C3E50"
headerColor = "#2C3E50"
buttonBackgroundColor = "#2C3E50"
buttonTextColor = "#FFFFFF"
warningBackgroundColor = "#F6B93B"
warningTextColor = "#FFFFFF"