[theme]
base="light"
primaryColor="#00b894"
backgroundColor="#faf9f6"
secondaryBackgroundColor="#e8e3d3"
textColor="#222222"
font="sans-serif"
pageBackgroundColor="#f5f3ea"
sidebarBackgroundColor="#e8e3d3"
headerColor="#00b894"
buttonBackgroundColor="#00b894"
buttonTextColor="#ffffff"
warningBackgroundColor="#f6b93b"
warningTextColor="#ffffff"
