[theme]
base="light"
primaryColor="#00b894"
backgroundColor="#fdfcf9"
secondaryBackgroundColor="#f2ebd3"
textColor="#222222"
font="sans-serif"
pageBackgroundColor="#f5f3ea"
sidebarBackgroundColor="#c7ecee"
headerColor="#00b894"
buttonBackgroundColor="#00b894"
buttonTextColor="#ffffff"
warningBackgroundColor="#f6b93b"
warningTextColor="#ffffff"
