[theme]
base="dark"
primaryColor="#00b894"
backgroundColor="#292F36"
secondaryBackgroundColor="#2C323D"
textColor="#FFFFFF"
font="sans serif"
pageBackgroundColor="#292F36"
sidebarBackgroundColor="#1E242B"
headerColor="#00b894"
buttonBackgroundColor="#00b894"
buttonTextColor="#FFFFFF"
warningBackgroundColor="#FF4136"
warningTextColor="#FFFFFF"
