[theme]
base = "light"
primaryColor = "#2C3E50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F2F2"
textColor = "#212121"
font = "serif"
pageBackgroundColor = "#FFFFFF"
sidebarBackgroundColor = "#2C3E50"
headerColor = "#2C3E50"
buttonBackgroundColor = "#2C3E50"
buttonTextColor = "#FFFFFF"
warningBackgroundColor = "#F6B93B"
warningTextColor = "#FFFFFF"
