[theme]
base="light"
primaryColor="#2ECC71"
backgroundColor="#F0F4F8"
secondaryBackgroundColor="#E5E9F0"
textColor="#34495E"
font="sans-serif"
pageBackgroundColor="#F0F4F8"
sidebarBackgroundColor="#D8E2EA"
headerColor="#2ECC71"
buttonBackgroundColor="#2ECC71"
buttonTextColor="#FFFFFF"
warningBackgroundColor="#FF4136"
warningTextColor="#FFFFFF"
