[theme]
base="light"
primaryColor="#00b894"
backgroundColor="#f1f8e9"
secondaryBackgroundColor="#dcedc8"
textColor="#2e4053"
font="sans-serif"
pageBackgroundColor="#e8f5e9"
sidebarBackgroundColor="#c8e6c9"
headerColor="#00b894"
buttonBackgroundColor="#00b894"
buttonTextColor="#ffffff"
warningBackgroundColor="#ff5722"
warningTextColor="#ffffff"

