[theme]
base = "light"
primaryColor = "#2C3E50"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#EAEAEA"
textColor = "#212121"
font = "sans-serif"
pageBackgroundColor = "#FFFFFF"
sidebarBackgroundColor = "#2C3E50"
headerColor = "#2C3E50"
buttonBackgroundColor = "#2C3E50"
buttonTextColor = "#FFFFFF"
warningBackgroundColor = "#F6B93B"
warningTextColor = "#FFFFFF"